### ISSUE TITLE
MacOS CI TODOs

### ISSUE THREAD

**Issue by viferga** [metacall/core#438]
## 🚀 Feature

- [ ] Enable funchook in the CI (https://github.com/metacall/core/blob/063219bdf29263d608c1a4a3e48291162408ac97/.github/workflows/macos-test.yml#L63)
- [ ] Enable backtrace in the CI
- [ ] Make the environment variables in metacall-environment.sh for MacOS do not depend on bash (https://github.com/metacall/core/blob/063219bdf29263d608c1a4a3e48291162408ac97/tools/metacall-environment.sh#L184 & https://github.com/metacall/core/blob/063219bdf29263d608c1a4a3e48291162408ac97/tools/metacall-environment.sh#L227)
- [ ] Fork nodejs library build or remove it and let the CI build nodejs library itself (https://github.com/metacall/core/blob/063219bdf29263d608c1a4a3e48291162408ac97/tools/metacall-environment.sh#L491)
- [ ] Create a matrix with Debug & Release and No sanitizers, Address sanitizer and Thread Sanitizer.
- [ ] Add the rest of languages.

**Comment by viferga** [comment]
@ahmedihabb2

**Comment by ahmedihabb2** [comment]
## TODOS (Cont.)

- [ ] FIX JNI and Java paths
- [ ] Handle unused variables
- [ ] Enable fork safe option

**Comment by ahmedihabb2** [comment]
> ##  Feature
> * [ ]  Enable funchook in the CI (https://github.com/metacall/core/blob/063219bdf29263d608c1a4a3e48291162408ac97/.github/workflows/macos-test.yml#L63
>   )
> * [ ]  Enable backtrace in the CI
> * [x]  Make the environment variables in metacall-environment.sh for MacOS do not depend on bash (https://github.com/metacall/core/blob/063219bdf29263d608c1a4a3e48291162408ac97/tools/metacall-environment.sh#L184
>    & https://github.com/metacall/core/blob/063219bdf29263d608c1a4a3e48291162408ac97/tools/metacall-environment.sh#L227
>   )
> * [ ]  Fork nodejs library build or remove it and let the CI build nodejs library itself (https://github.com/metacall/core/blob/063219bdf29263d608c1a4a3e48291162408ac97/tools/metacall-environment.sh#L491
>   )
> * [ ]  Create a matrix with Debug & Release and No sanitizers, Address sanitizer and Thread Sanitizer.
> * [x]  Add the rest of languages (Cobol). -> [Build MetaCall with Cobol Support for macOS #439](https://github.com/metacall/core/pull/439)
> * [ ]  Add the rest of languages (C).
> * [ ]  Add the rest of languages (Rust).
> * [ ]  Add ports (Swig dependant ones (Ruby), Go, ...).

**Comment by viferga** [comment]
Funchook, now PLTHook, and NodeJS distribution solved.
